apiVersion: v1
kind: Namespace
metadata:
  name: redemption
  labels:
    name: redemption
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redemption-app
  namespace: redemption
  annotations:
    # Replace with the app_irsa_role_arn Terraform output.
    eks.amazonaws.com/role-arn: "arn:aws:iam::<ACCOUNT_ID>:role/the-redemption-app-sa"
automountServiceAccountToken: true
